language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run lint
  - npm run test:ci
  - npm run deploy:react
deploy:
  provider: pages
  local-dir: dist
  keep-history: false
  skip-cleanup: true
  # Set in the settings page of your repository, as a secure variable
  github-token: $GITHUB_TOKEN
  on:
    branch: master
cache:
  directories:
    - "node_modules"
